Consider text/plain when calling notebook.cell_output_text(idx)
nteract/testbook pull request #104
Opened 2021-05-20 08:26 UTC by nastra

We have a use case where the cell output is some Pandas output and when
calling `notebook.cell_output_text(..)` we only get empty output, even
though `output["data"]["text/plain"]` contains actually the expected
text.

2021-05-20 19:33 UTC, MSeal requested changes
Thanks for the description of the problem and the improvement. Could we get an example input put into the tests to make sure we don't break this accidentally in the future? Thanks!

2021-05-25 06:58 UTC, nastra commented
@MSeal sure thing. I added a small example with a test that shows the problem

2021-06-02 16:42 UTC, nastra commented
@MSeal can you take another look at the proposed changes when you get a chance?

2021-06-02 19:41 UTC, MSeal approved these changes

2021-06-02 19:41 UTC, MSeal commented on requirements-dev.txt
> +pandas==1.2.4
Probably should be a `>=` dep but I can change that later

2021-06-02 19:41 UTC, MSeal commented
Thanks @nastra -- I'll look at shipping a patch release with the change so it's readily available.

2021-06-02 19:52 UTC, merged