Added skip feature
nteract/testbook pull request #142
Opened 2022-04-16 15:28 UTC by SagiPolaczek

#141 

This is the implementation I came up with.

2022-05-23 10:05 UTC, rohitsanj commented
@SagiPolaczek Thanks for raising this PR! I apologize for not having reviewed this yet, I will jump on this ASAP.

2022-05-23 10:32 UTC, rohitsanj commented
I wonder why CI hasn't been triggered on this PR. Strange.

2022-05-23 10:41 UTC, rohitsanj commented
@SagiPolaczek can you please try pushing an empty commit using `git commit --allow-empty -m "Trigger GitHub CI"`?

2022-05-23 11:39 UTC, rohitsanj requested changes
Minor comments.

Also, please add some unit tests to `testbook/tests/test_client.py` for when `skip` is: `int`, `str`, `list[int]`, `[list[str]`.

Thanks again!

2022-05-23 11:39 UTC, rohitsanj commented on testbook/client.py
> +
We would also want to accept cell tag(s) as input for the `skip` argument for users who wouldn't want to concern themselves with knowing which index each cell is at.

```suggestion
            if isinstance(skip, int) or isinstance(skip, str):
                skip = [skip]

            if all(isinstance(x, str) for x in skip):
                skip = [self._cell_index(tag) for tag in skip]

```

2022-05-23 11:39 UTC, rohitsanj commented on testbook/client.py
> +        Executes all cells besides the ones who were asked to be skipped
```suggestion
        Executes all cells.
        
        If skip is passed, we will remove those cell(s) from the list of cells to be executed.
```

2022-12-07 00:06 UTC, rohitsanj commented
Sure, @rprater! Thanks.

2022-12-07 13:12 UTC, SagiPolaczek commented
Sorry, I totally missed it and moved on!

Thanks @rohitsanj for taking it and thanks @rohitsanj for maintaining the repo.

2024-03-16 15:21 UTC, SagiPolaczek commented
I'm closing all of my inactive PRs. 

Thanks!

2024-03-16 15:21 UTC, closed without merging